#!/usr/bin/env python3

"""
    psud
    PSU information update daemon for SONiC
    This daemon will loop to collect PSU related information and then write the information to state DB.
    Currently it is implemented based on old plugins rather than new platform APIs. So the PSU information just
    includes three things: number of PSU, PSU presence and PSU status which is supported by old plugins.
    The loop interval is PSU_INFO_UPDATE_PERIOD_SECS in seconds.
"""

import signal
import sys
import threading
from datetime import datetime

from sonic_platform.psu import Psu
from sonic_py_common import daemon_base, logger
from swsscommon import swsscommon


#
# Constants ====================================================================
#

# TODO: Once we no longer support Python 2, we can eliminate this and get the
# name using the 'name' field (e.g., `signal.SIGINT.name`) starting with Python 3.5
SIGNALS_TO_NAMES_DICT = dict((getattr(signal, n), n)
                             for n in dir(signal) if n.startswith('SIG') and '_' not in n)

SYSLOG_IDENTIFIER = "psud"

PLATFORM_SPECIFIC_MODULE_NAME = "psuutil"
PLATFORM_SPECIFIC_CLASS_NAME = "PsuUtil"

CHASSIS_INFO_TABLE = 'CHASSIS_INFO'
CHASSIS_INFO_KEY = 'chassis 1'
CHASSIS_INFO_PSU_NUM_FIELD = 'psu_num'
CHASSIS_INFO_PDB_NUM_FIELD = 'pdb_num'

CHASSIS_INFO_POWER_CONSUMER_FIELD = 'Consumed Power {}'
CHASSIS_INFO_POWER_SUPPLIER_FIELD = 'Supplied Power {}'
CHASSIS_INFO_TOTAL_POWER_CONSUMED_FIELD = 'Total Consumed Power'
CHASSIS_INFO_TOTAL_POWER_SUPPLIED_FIELD = 'Total Supplied Power'
CHASSIS_INFO_POWER_KEY_TEMPLATE = 'chassis_power_budget {}'

PSU_INFO_TABLE = 'PSU_INFO'
PSU_INFO_KEY_TEMPLATE = 'PSU {}'
PSU_INFO_PRESENCE_FIELD = 'presence'
PSU_INFO_MODEL_FIELD = 'model'
PSU_INFO_SERIAL_FIELD = 'serial'
PSU_INFO_REV_FIELD = 'revision'
PSU_INFO_STATUS_FIELD = 'status'
PSU_INFO_TEMP_FIELD = 'temp'
PSU_INFO_TEMP_TH_FIELD = 'temp_threshold'
PSU_INFO_VOLTAGE_FIELD = 'voltage'
PSU_INFO_VOLTAGE_MAX_TH_FIELD = 'voltage_max_threshold'
PSU_INFO_VOLTAGE_MIN_TH_FIELD = 'voltage_min_threshold'
PSU_INFO_CURRENT_FIELD = 'current'
PSU_INFO_POWER_FIELD = 'power'
PSU_INFO_POWER_OVERLOAD = 'power_overload'
PSU_INFO_POWER_WARNING_SUPPRESS_THRESHOLD = 'power_warning_suppress_threshold'
PSU_INFO_POWER_CRITICAL_THRESHOLD = 'power_critical_threshold'
PSU_INFO_FRU_FIELD = 'is_replaceable'
PSU_INFO_IN_VOLTAGE_FIELD = 'input_voltage'
PSU_INFO_IN_CURRENT_FIELD = 'input_current'
PSU_INFO_POWER_MAX_FIELD = 'max_power'
PSU_INFO_TIMESTAMP_FIELD = 'timestamp'

PDB_INFO_KEY_TEMPLATE = 'PDB {}'

PHYSICAL_ENTITY_INFO_TABLE = 'PHYSICAL_ENTITY_INFO'

FAN_INFO_TABLE = 'FAN_INFO'
FAN_INFO_PRESENCE_FIELD = 'presence'
FAN_INFO_STATUS_FIELD = 'status'
FAN_INFO_DIRECTION_FIELD = 'direction'
FAN_INFO_SPEED_FIELD = 'speed'
FAN_INFO_LED_STATUS_FIELD = 'led_status'
FAN_INFO_TIMESTAMP_FIELD = 'timestamp'

NOT_AVAILABLE = 'N/A'
UPDATING_STATUS = 'Updating'

PSU_INFO_UPDATE_PERIOD_SECS = 3

PSUUTIL_LOAD_ERROR = 1
PSU_DB_CONNECT_ERROR = 2

platform_psuutil = None
platform_chassis = None

exit_code = 0

# temporary wrappers that are compliable with both new platform api and old-style plugin mode


def _wrapper_get_num_psus(logger):
    """Get total number of PSUs when using psuutil; total PSUs+PDBs when using chassis (for __del__ iteration)."""
    if platform_chassis is not None:
        try:
            n_psu = platform_chassis.get_num_psus()
        except NotImplementedError:
            n_psu = 0
        try:
            n_pdb = platform_chassis.get_num_pdbs()
        except NotImplementedError:
            n_pdb = 0
        return n_psu + n_pdb
    if platform_psuutil is not None:
        return platform_psuutil.get_num_psus()
    if logger:
        logger.log_warning("PSU provider unavailable; defaulting to 0 PSUs")
    return 0


def _wrapper_get_psu(logger, psu_index):
    """
    Get PSU object from platform chassis
    :param logger: Logger instance for error/warning messages
    :param psu_index: PSU index (1-based)
    :return: PSU object if available, None otherwise
    """
    if platform_chassis is None:
        return None
    if psu_index < 1:
        return None
    try:
        psu = platform_chassis.get_psu(psu_index - 1)
        if psu is not None:
            return psu
    except NotImplementedError:
        if logger:
            logger.log_warning("get_psu() not implemented by platform chassis: Not implemented")
    except Exception as e:
        if logger:
            logger.log_error("Failed to get PSU {} from platform chassis: {}".format(psu_index, str(e)))
    return None


def _wrapper_get_pdb(logger, pdb_index):
    """
    Get PDB object from platform chassis
    :param logger: Logger instance for error/warning messages
    :param pdb_index: PDB index (1-based)
    :return: PDB object if available, None otherwise
    """
    if platform_chassis is None:
        return None
    if pdb_index < 1:
        return None
    try:
        pdb = platform_chassis.get_pdb(pdb_index - 1)
        if pdb is not None:
            return pdb
    except NotImplementedError:
        if logger:
            logger.log_warning("get_pdb() not implemented by platform chassis: Not implemented")
    except Exception as e:
        if logger:
            logger.log_error("Failed to get PDB {} from platform chassis: {}".format(pdb_index, str(e)))
    return None


def _wrapper_get_psu_presence(logger, psu_index):
    if platform_chassis is not None:
        psu = _wrapper_get_psu(logger, psu_index)
        if psu:
            try:
                return psu.get_presence()
            except NotImplementedError:
                pass
            except Exception as e:
                if logger:
                    logger.log_warning("Exception in psu.get_presence() for PSU {}: {}".format(psu_index, str(e)))
                return False
    if platform_psuutil is not None:
        try:
            return platform_psuutil.get_psu_presence(psu_index)
        except Exception as e:
            if logger:
                logger.log_warning("Exception in platform_psuutil.get_psu_presence({}): {}".format(psu_index, str(e)))
            return False
    if logger:
        logger.log_error("Failed to get PSU {} presence".format(psu_index))
    return False


def _wrapper_get_pdb_presence(logger, pdb_index):
    if platform_chassis is None:
        return False
    pdb = _wrapper_get_pdb(logger, pdb_index)
    if not pdb:
        return False
    try:
        return pdb.get_presence()
    except NotImplementedError:
        return False
    except Exception as e:
        if logger:
            logger.log_warning("Exception in pdb.get_presence() for PDB {}: {}".format(pdb_index, str(e)))
        return False


def _wrapper_get_psu_status(logger, psu_index):
    if platform_chassis is not None:
        psu = _wrapper_get_psu(logger, psu_index)
        if psu:
            try:
                return psu.get_powergood_status()
            except NotImplementedError:
                pass
            except Exception as e:
                if logger:
                    logger.log_warning("Exception in psu.get_powergood_status() for PSU {}: {}".format(psu_index, str(e)))
                return False
    if platform_psuutil is not None:
        try:
            return platform_psuutil.get_psu_status(psu_index)
        except Exception as e:
            if logger:
                logger.log_warning("Exception in platform_psuutil.get_psu_status({}): {}".format(psu_index, str(e)))
            return False
    if logger:
        logger.log_error("Failed to get PSU {} status".format(psu_index))
    return False


def _wrapper_get_pdb_status(logger, pdb_index):
    if platform_chassis is None:
        return False
    pdb = _wrapper_get_pdb(logger, pdb_index)
    if not pdb:
        return False
    try:
        return pdb.get_powergood_status()
    except NotImplementedError:
        return False
    except Exception as e:
        if logger:
            logger.log_warning("Exception in pdb.get_powergood_status() for PDB {}: {}".format(pdb_index, str(e)))
        return False


#
# Helper functions =============================================================
#

def get_psu_key(psu_index):
    """Return PSU_INFO key (object name) for 1-based PSU index. Used for legacy psuutil path."""
    psu = _wrapper_get_psu(None, psu_index)
    if psu is not None:
        try:
            return psu.get_name()
        except Exception:
            pass
    return PSU_INFO_KEY_TEMPLATE.format(psu_index)


def get_pdb_key(pdb_index):
    """Return PDB_INFO_KEY_TEMPLATE key (object name) for 1-based PDB index."""
    pdb = _wrapper_get_pdb(None, pdb_index)
    if pdb is not None:
        try:
            return pdb.get_name()
        except Exception:
            pass
    return PDB_INFO_KEY_TEMPLATE.format(pdb_index)


# try get information from platform API and return a default value if we catch NotImplementedError
def try_get(callback, default=None):
    """
    Handy function to invoke the callback and catch any exceptions.

    Note: Exceptions are handled silently to prioritize daemon stability over observability.
    This function is used for non-critical status reads (e.g., temperature, serial number).
    For critical operations requiring error visibility, use dedicated wrapper functions
    like _wrapper_get_psu_presence() which log exceptions before returning defaults.

    :param callback: Callback to be invoked
    :param default: Default return value if exception occur
    :return: Default return value if exception occur else return value of the callback
    """
    try:
        ret = callback()
        if ret is None:
            ret = default
    except NotImplementedError:
        ret = default
    except Exception:
        ret = default

    return ret


def _sum_system_power_from_other_psus_and_pdbs(chassis, entity, system_power):
    """
    Add get_power() from every other PSU and every other PDB to system_power.
    Uses two separate loops (does not build a combined PSUs+PDBs list).
    """
    try:
        for other in chassis.get_all_psus():
            if other is not entity:
                power_str = try_get(other.get_power, NOT_AVAILABLE)
                if power_str != NOT_AVAILABLE:
                    system_power += float(power_str)
    except NotImplementedError:
        pass
    try:
        for other in chassis.get_all_pdbs():
            if other is not entity:
                power_str = try_get(other.get_power, NOT_AVAILABLE)
                if power_str != NOT_AVAILABLE:
                    system_power += float(power_str)
    except NotImplementedError:
        pass
    return system_power


def log_on_status_changed(logger, normal_status, normal_log, abnormal_log):
    """
    Log when any status changed
    :param logger: Logger object.
    :param normal_status: Expected status.
    :param normal_log: Log string for expected status.
    :param abnormal_log: Log string for unexpected status
    :return:
    """
    if normal_status:
        logger.log_notice(normal_log)
    else:
        logger.log_warning(abnormal_log)

#
# PSU Chassis Info ==========================================================
#


class PsuChassisInfo(logger.Logger):

    def __init__(self, log_identifier, chassis):
        """
        Constructor for PsuChassisInfo
        :param chassis: Object representing a platform chassis
        """
        super(PsuChassisInfo, self).__init__(log_identifier)

        self.chassis = chassis
        self.first_run = True
        self.master_status_good = True
        self.total_consumed_power = 0.0
        self.total_supplied_power = 0.0

    def run_power_budget(self, chassis_tbl):
        self.total_supplied_power = 0.0
        self.total_consumed_power = 0.0
        total_supplied_power = 0.0
        total_fan_consumed_power = 0.0
        total_module_consumed_power = 0.0

        dict_index = 0
        total_entries_len = 2  # For total supplied and consumed
        psu_list = []
        pdb_list = []
        try:
            psu_list = list(self.chassis.get_all_psus())
            pdb_list = list(self.chassis.get_all_pdbs())
        except NotImplementedError:
            pdb_list = []
            try:
                psu_list = list(self.chassis.get_all_psus())
            except NotImplementedError:
                psu_list = []
        num_suppliers = len(psu_list) + len(pdb_list)
        dict_len = num_suppliers +\
            self.chassis.get_num_fan_drawers() +\
            self.chassis.get_num_modules() + \
            total_entries_len

        fvs = swsscommon.FieldValuePairs(dict_len)

        def _process_power_supplier(supplier, index, default_prefix):
            nonlocal dict_index, total_supplied_power
            name = try_get(supplier.get_name, '{} {}'.format(default_prefix, index + 1))
            presence = try_get(supplier.get_presence)
            if not presence:
                try:
                    chassis_tbl.hdel(CHASSIS_INFO_POWER_KEY_TEMPLATE.format(1), CHASSIS_INFO_POWER_SUPPLIER_FIELD.format(name))
                except RuntimeError as e:
                    self.log_error("Failed to delete {} power info from DB: {}".format(name, e))
                return

            power_good = try_get(supplier.get_powergood_status)
            if not power_good:
                supplied_power = 0.0
                fvs[dict_index] = (CHASSIS_INFO_POWER_SUPPLIER_FIELD.format(name), str(supplied_power))
                dict_index += 1
                return

            supplied_power = try_get(supplier.get_maximum_supplied_power, 0.0)
            total_supplied_power = total_supplied_power + supplied_power
            fvs[dict_index] = (CHASSIS_INFO_POWER_SUPPLIER_FIELD.format(name), str(supplied_power))
            dict_index += 1

        for index, supplier in enumerate(psu_list):
            _process_power_supplier(supplier, index, 'PSU')
        for index, supplier in enumerate(pdb_list):
            _process_power_supplier(supplier, index, 'PDB')

        for index, power_consumer in enumerate(self.chassis.get_all_fan_drawers()):
            presence = try_get(power_consumer.get_presence)
            name = try_get(power_consumer.get_name, 'FAN-DRAWER {}'.format(index))
            if not presence:
                try:
                    chassis_tbl.hdel(CHASSIS_INFO_POWER_KEY_TEMPLATE.format(1), CHASSIS_INFO_POWER_CONSUMER_FIELD.format(name))
                except RuntimeError as e:
                    self.log_error("Failed to delete fan drawer {} power info from DB: {}".format(name, e))
                continue

            fan_drawer_power = try_get(power_consumer.get_maximum_consumed_power, 0.0)
            total_fan_consumed_power = total_fan_consumed_power + fan_drawer_power
            fvs[dict_index] = (CHASSIS_INFO_POWER_CONSUMER_FIELD.format(name), str(fan_drawer_power))
            dict_index += 1

        for index, power_consumer in enumerate(self.chassis.get_all_modules()):
            presence = try_get(power_consumer.get_presence)
            name = try_get(power_consumer.get_name, 'MODULE {}'.format(index))
            if not presence:
                try:
                    chassis_tbl.hdel(CHASSIS_INFO_POWER_KEY_TEMPLATE.format(1), CHASSIS_INFO_POWER_CONSUMER_FIELD.format(name))
                except RuntimeError as e:
                    self.log_error("Failed to delete module {} power info from DB: {}".format(name, e))
                continue

            module_power = try_get(power_consumer.get_maximum_consumed_power, 0.0)
            total_module_consumed_power = total_module_consumed_power + module_power
            fvs[dict_index] = (CHASSIS_INFO_POWER_CONSUMER_FIELD.format(name), str(module_power))
            dict_index += 1

        # Record total supplied and consumed power
        self.total_supplied_power = total_supplied_power
        self.total_consumed_power = total_fan_consumed_power + total_module_consumed_power

        # Record in state DB in chassis table
        fvs[dict_index] = (CHASSIS_INFO_TOTAL_POWER_SUPPLIED_FIELD, str(self.total_supplied_power))
        fvs[dict_index + 1] = (CHASSIS_INFO_TOTAL_POWER_CONSUMED_FIELD, str(self.total_consumed_power))
        try:
            chassis_tbl.set(CHASSIS_INFO_POWER_KEY_TEMPLATE.format(1), fvs)
        except RuntimeError as e:
            self.log_error("Failed to update chassis power budget to DB: {}".format(e))

    def update_master_status(self):
        set_led = self.first_run
        master_status_good = False

        if self.total_supplied_power != 0.0 and self.total_consumed_power != 0.0:
            master_status_good = (self.total_consumed_power < self.total_supplied_power)
            if master_status_good != self.master_status_good:
                set_led = True

            self.master_status_good = master_status_good

        if set_led:
            # Update the PSU master status LED
            # set_status_master_led() is a class method implemented in PsuBase
            # so we do not need to catch NotImplementedError here
            color = Psu.STATUS_LED_COLOR_GREEN if master_status_good else Psu.STATUS_LED_COLOR_RED
            Psu.set_status_master_led(color)

            log_on_status_changed(self, self.master_status_good,
                                  'PSU supplied power warning cleared: supplied power is back to normal.',
                                  'PSU supplied power warning: {}W supplied-power less than {}W consumed-power'.format(
                                      self.total_supplied_power, self.total_consumed_power)
                                  )
        if self.first_run:
            self.first_run = False

        return set_led

# PSU status ===================================================================
#


class PsuStatus(object):
    def __init__(self, logger, entity, name):
        """entity: PSU or PDB object (PsuBase/PdbBase). name: DB key e.g. 'PSU 1' or 'PDB 1'."""
        self.psu = entity
        self.psu_index = name  # used in log messages
        self.presence = True
        self.power_good = True
        self.voltage_good = True
        self.temperature_good = True
        self.check_psu_power_threshold = False
        self.power_exceeded_threshold = False
        self.logger = logger

    def set_presence(self, presence):
        """
        Set and cache PSU presence status
        :param presence: PSU presence status
        :return: True if status changed else False
        """
        if presence == self.presence:
            return False

        self.presence = presence
        return True

    def set_power_good(self, power_good):
        """
        Set and cache PSU power good status
        :param power_good: PSU power good status
        :return: True if status changed else False
        """
        if power_good == self.power_good:
            return False

        self.power_good = power_good
        return True

    def set_voltage(self, voltage, high_threshold, low_threshold):
        if voltage == NOT_AVAILABLE or high_threshold == NOT_AVAILABLE or low_threshold == NOT_AVAILABLE:
            if self.voltage_good is not True:
                self.logger.log_warning('PSU {} voltage or high_threshold or low_threshold become unavailable, '
                                        'voltage={}, high_threshold={}, low_threshold={}'.format(self.psu_index, voltage, high_threshold, low_threshold))
                self.voltage_good = True
            return False

        voltage_good = (low_threshold <= voltage <= high_threshold)
        if voltage_good == self.voltage_good:
            return False

        self.voltage_good = voltage_good
        return True

    def set_temperature(self, temperature, high_threshold):
        if temperature == NOT_AVAILABLE or high_threshold == NOT_AVAILABLE:
            if self.temperature_good is not True:
                self.logger.log_warning('PSU {} temperature or high_threshold become unavailable, '
                                        'temperature={}, high_threshold={}'.format(self.psu_index, temperature, high_threshold))
                self.temperature_good = True
            return False

        temperature_good = (temperature < high_threshold)
        if temperature_good == self.temperature_good:
            return False

        self.temperature_good = temperature_good
        return True

    def set_power_exceed_threshold(self, power_exceeded_threshold):
        if power_exceeded_threshold == self.power_exceeded_threshold:
            return False

        self.power_exceeded_threshold = power_exceeded_threshold
        return True

    def is_ok(self):
        return self.presence and self.power_good and self.voltage_good and self.temperature_good


#
# Daemon =======================================================================
#

class DaemonPsud(daemon_base.DaemonBase):
    def __init__(self, log_identifier):
        super(DaemonPsud, self).__init__(log_identifier)

        # Set minimum logging level to INFO
        self.set_min_log_priority_info()

        self.stop_event = threading.Event()
        self.num_psus = 0
        self.psu_status_dict = {}
        self.chassis_tbl = None
        self.fan_tbl = None
        self.psu_tbl = None
        self.psu_chassis_info = None
        self.first_run = True
        self.psu_threshold_exceeded_logged = False

        global platform_psuutil
        global platform_chassis

        # Load new platform api class
        try:
            import sonic_platform.platform
            platform_chassis = sonic_platform.platform.Platform().get_chassis()
        except Exception as e:
            self.log_warning("Failed to load chassis due to {}".format(repr(e)))

        # Load platform-specific psuutil class
        if platform_chassis is None:
            try:
                platform_psuutil = self.load_platform_util(PLATFORM_SPECIFIC_MODULE_NAME, PLATFORM_SPECIFIC_CLASS_NAME)
            except Exception as e:
                self.log_error("Failed to load psuutil: %s" % (str(e)), True)
                sys.exit(PSUUTIL_LOAD_ERROR)

        # Connect to STATE_DB and create psu/chassis info tables
        try:
            state_db = daemon_base.db_connect("STATE_DB")
            self.chassis_tbl = swsscommon.Table(state_db, CHASSIS_INFO_TABLE)
            self.psu_tbl = swsscommon.Table(state_db, PSU_INFO_TABLE)
            self.fan_tbl = swsscommon.Table(state_db, FAN_INFO_TABLE)
            self.phy_entity_tbl = swsscommon.Table(state_db, PHYSICAL_ENTITY_INFO_TABLE)
        except Exception as e:
            self.log_error("Failed to connect to STATE_DB: {}".format(e))
            sys.exit(PSU_DB_CONNECT_ERROR)

        # Post psu/pdb number info to STATE_DB (once at boot/reload)
        self.num_psus = _wrapper_get_num_psus(self)
        num_psus_chassis = 0
        num_pdbs_chassis = 0
        self.all_power_entity_names = []
        if platform_chassis is not None:
            try:
                num_psus_chassis = platform_chassis.get_num_psus()
                self.all_power_entity_names.extend([p.get_name() for p in platform_chassis.get_all_psus()])
            except NotImplementedError:
                pass
            try:
                num_pdbs_chassis = platform_chassis.get_num_pdbs()
                self.all_power_entity_names.extend([p.get_name() for p in platform_chassis.get_all_pdbs()])
            except NotImplementedError:
                pass
        fvs = swsscommon.FieldValuePairs([
            (CHASSIS_INFO_PSU_NUM_FIELD, str(num_psus_chassis)),
            (CHASSIS_INFO_PDB_NUM_FIELD, str(num_pdbs_chassis)),
        ])
        try:
            self.chassis_tbl.set(CHASSIS_INFO_KEY, fvs)
        except RuntimeError as e:
            self.log_error("Failed to set PSU/PDB number to DB: {}".format(e))

    def __del__(self):
        # Delete all the information from DB and then exit. Do not use log_error here:
        # during interpreter shutdown logging may be broken and can raise.
        psu_tbl = getattr(self, 'psu_tbl', None)
        phy_entity_tbl = getattr(self, 'phy_entity_tbl', None)

        def _del_phy_entity(key):
            if phy_entity_tbl is None:
                return
            try:
                if phy_entity_tbl.get(key) is not None:
                    phy_entity_tbl._del(key)
            except Exception:
                pass

        if psu_tbl is not None:
            names = getattr(self, 'all_power_entity_names', None)
            if names:
                for name in names:
                    try:
                        psu_tbl._del(name)
                    except Exception:
                        pass
                    _del_phy_entity(name)
            else:
                for psu_index in range(1, getattr(self, 'num_psus', 0) + 1):
                    key = get_psu_key(psu_index)
                    try:
                        psu_tbl._del(key)
                    except Exception:
                        pass
                    _del_phy_entity(key)

        if getattr(self, 'chassis_tbl', None) is not None:
            try:
                self.chassis_tbl._del(CHASSIS_INFO_KEY)
            except Exception:
                pass
            try:
                self.chassis_tbl._del(CHASSIS_INFO_POWER_KEY_TEMPLATE.format(1))
            except Exception:
                pass

    # Override signal handler from DaemonBase
    def signal_handler(self, sig, frame):
        FATAL_SIGNALS = [signal.SIGINT, signal.SIGTERM]
        NONFATAL_SIGNALS = [signal.SIGHUP]

        global exit_code

        if sig in FATAL_SIGNALS:
            self.log_info("Caught signal '{}' - exiting...".format(SIGNALS_TO_NAMES_DICT[sig]))
            exit_code = 128 + sig  # Make sure we exit with a non-zero code so that supervisor will try to restart us
            self.stop_event.set()
        elif sig in NONFATAL_SIGNALS:
            self.log_info("Caught signal '{}' - ignoring...".format(SIGNALS_TO_NAMES_DICT[sig]))
        else:
            self.log_warning("Caught unhandled signal '{}' - ignoring...".format(SIGNALS_TO_NAMES_DICT[sig]))

    # Main daemon logic
    def run(self):
        if self.stop_event.wait(PSU_INFO_UPDATE_PERIOD_SECS):
            # We received a fatal signal
            return False

        # Update predefined position_in_parent and parent_name for PSU
        # it was in the __init__ function which means will be run only once
        # But there's chance that the keys(PHYSICAL_ENTITY_INFO|*) got removed by other processes,
        # like the exit function during the restart of thermalctld,
        # hence move it to the iteration run, so the key will be filled again after removed.
        self._update_psu_entity_info()

        self.psu_threshold_exceeded_logged = False
        self.update_psu_data()
        self.update_pdb_data()
        self._update_led_color()

        if platform_chassis and platform_chassis.is_modular_chassis():
            self.update_psu_chassis_info()

        if self.first_run:
            self.first_run = False

        return True

    def update_psu_data(self):
        if not platform_chassis:
            return

        try:
            for psu in platform_chassis.get_all_psus():
                try:
                    self._update_single_psu_data(psu)
                except Exception as e:
                    self.log_warning("Failed to update PSU data - {}".format(e))
        except NotImplementedError:
            pass

    def update_pdb_data(self):
        if not platform_chassis:
            return

        try:
            for pdb in platform_chassis.get_all_pdbs():
                try:
                    self._update_single_pdb_data(pdb)
                except Exception as e:
                    self.log_warning("Failed to update PDB data - {}".format(e))
        except NotImplementedError:
            pass

    def _update_single_psu_data(self, entity):
        """Update STATE_DB for one PSU (PsuBase)."""
        self._update_single_power_entity_data(entity, 'psu')

    def _update_single_pdb_data(self, entity):
        """Update STATE_DB for one PDB (PdbBase)."""
        self._update_single_power_entity_data(entity, 'pdb')

    def _update_single_power_entity_data(self, entity, kind):
        """
        Shared STATE_DB update for one PSU or PDB. kind is 'psu' or 'pdb'.
        """
        label = 'PSU' if kind == 'psu' else 'PDB'
        name = try_get(entity.get_name, NOT_AVAILABLE)
        if name == NOT_AVAILABLE:
            idx = getattr(entity, 'index', 'unknown')
            name = '{} {}'.format(label, idx) if isinstance(idx, int) else str(idx)
        presence = try_get(entity.get_presence, False)
        power_good = try_get(entity.get_powergood_status, False) if presence else False
        voltage = NOT_AVAILABLE
        voltage_high_threshold = NOT_AVAILABLE
        voltage_low_threshold = NOT_AVAILABLE
        temperature = NOT_AVAILABLE
        temperature_threshold = NOT_AVAILABLE
        current = NOT_AVAILABLE
        power = NOT_AVAILABLE
        is_replaceable = try_get(entity.is_replaceable, False)
        in_voltage = NOT_AVAILABLE
        in_current = NOT_AVAILABLE
        max_power = NOT_AVAILABLE
        if presence:
            voltage = try_get(entity.get_voltage, NOT_AVAILABLE)
            voltage_high_threshold = try_get(entity.get_voltage_high_threshold, NOT_AVAILABLE)
            voltage_low_threshold = try_get(entity.get_voltage_low_threshold, NOT_AVAILABLE)
            temperature = try_get(entity.get_temperature, NOT_AVAILABLE)
            temperature_threshold = try_get(entity.get_temperature_high_threshold, NOT_AVAILABLE)
            current = try_get(entity.get_current, NOT_AVAILABLE)
            power = try_get(entity.get_power, NOT_AVAILABLE)
            in_current = try_get(entity.get_input_current, NOT_AVAILABLE)
            in_voltage = try_get(entity.get_input_voltage, NOT_AVAILABLE)
            max_power = try_get(entity.get_maximum_supplied_power, NOT_AVAILABLE)

        if name not in self.psu_status_dict:
            self.psu_status_dict[name] = PsuStatus(self, entity, name)

        psu_status = self.psu_status_dict[name]
        set_led = self.first_run
        presence_changed = psu_status.set_presence(presence)
        if presence_changed:
            set_led = True
            log_on_status_changed(self, psu_status.presence,
                                  '{} absence warning cleared: {} is inserted back.'.format(label, name),
                                  '{} absence warning: {} is not present.'.format(label, name)
                                  )
            if not psu_status.presence:
                 psu_status.check_psu_power_threshold = False
            if not psu_status.presence:
                self.log_error("{} is not present.".format(name))
        elif self.first_run and not presence:
            self.log_error("{} is not present.".format(name))

        if presence_changed or self.first_run:
            # Have to update PSU fan data here because PSU presence status changed. If we don't
            # update PSU fan data here, there might be an inconsistent output between "show platform psustatus"
            # and "show platform fan". For example, say PSU 1 is removed, and psud query PSU status every 3 seconds,
            # it will update PSU state to "Not OK" and PSU LED to "red"; but thermalctld query PSU fan status
            # every 60 seconds, it may still treat PSU state to "OK" and PSU LED to "red".
            self._update_psu_fan_data(entity)

        power_good_changed = psu_status.set_power_good(power_good)
        if presence and power_good_changed:
            set_led = True
            log_on_status_changed(self, psu_status.power_good,
                                  'Power absence warning cleared: {} power is back to normal.'.format(name),
                                  'Power absence warning: {} is out of power.'.format(name)
                                  )

        if presence and power_good_changed or self.first_run:
            psu_status.check_psu_power_threshold = False
            if psu_status.power_good:
                # power_good has been updated and it is True, which means it was False
                # Initialize power exceeding threshold state in this case
                if (try_get(entity.get_psu_power_critical_threshold) and try_get(entity.get_psu_power_warning_suppress_threshold) and power != NOT_AVAILABLE):
                    psu_status.check_psu_power_threshold = True

        power_exceeded_threshold = psu_status.power_exceeded_threshold
        power_warning_suppress_threshold = try_get(entity.get_psu_power_warning_suppress_threshold, NOT_AVAILABLE)
        power_critical_threshold = try_get(entity.get_psu_power_critical_threshold, NOT_AVAILABLE)
        if psu_status.check_psu_power_threshold:
            # Calculate total power from all power entities (PSUs + PDBs)
            system_power = _sum_system_power_from_other_psus_and_pdbs(platform_chassis, entity, float(power))

            if power_warning_suppress_threshold == NOT_AVAILABLE or power_critical_threshold == NOT_AVAILABLE:
                self.log_error("PSU power thresholds become invalid: threshold {} critical threshold {}".format(power_warning_suppress_threshold, power_critical_threshold))
                psu_status.check_psu_power_threshold = False
                psu_status.power_exceeded_threshold = False
            elif psu_status.power_exceeded_threshold:
                # The failing threshold is the warning threshold
                if system_power < power_warning_suppress_threshold:
                    # Clear alarm
                    power_exceeded_threshold = False
            else:
                # The rising threshold is the critical threshold
                if system_power >= power_critical_threshold:
                    # Raise alarm
                    power_exceeded_threshold = True

            if psu_status.set_power_exceed_threshold(power_exceeded_threshold) and not self.psu_threshold_exceeded_logged:
                # Since this is a system level PSU power exceeding check, we do not need to log it for each PSU
                log_on_status_changed(self, not psu_status.power_exceeded_threshold,
                                      'PSU power warning cleared: system power {} is back to normal, below the warning suppress threshold {}.'.format(system_power, power_warning_suppress_threshold),
                                      'PSU power warning: system power {} exceeds the critical threshold {}.'.format(system_power, power_critical_threshold))
                self.psu_threshold_exceeded_logged = True

        if presence and psu_status.set_voltage(voltage, voltage_high_threshold, voltage_low_threshold):
            set_led = True
            log_on_status_changed(self, psu_status.voltage_good,
                                  'Voltage warning cleared: {} voltage is back to normal.'.format(name),
                                  'Voltage warning: {} voltage out of range, current voltage={}, valid range=[{}, {}].'.format(
                                      name, voltage, voltage_high_threshold, voltage_low_threshold)
                                  )

        if presence and psu_status.set_temperature(temperature, temperature_threshold):
            set_led = True
            log_on_status_changed(self, psu_status.temperature_good,
                                  'Temperature warning cleared: {} temperature is back to normal.'.format(name),
                                  'Temperature warning: {} temperature too hot, temperature={}, threshold={}.'.format(
                                      name, temperature, temperature_threshold)
                                  )

        if set_led:
            self._set_psu_led(entity, psu_status)

        fvs = swsscommon.FieldValuePairs(
            [(PSU_INFO_MODEL_FIELD, str(try_get(entity.get_model, NOT_AVAILABLE))),
             (PSU_INFO_SERIAL_FIELD, str(try_get(entity.get_serial, NOT_AVAILABLE))),
             (PSU_INFO_REV_FIELD, str(try_get(entity.get_revision, NOT_AVAILABLE))),
             (PSU_INFO_TEMP_FIELD, str(temperature)),
             (PSU_INFO_TEMP_TH_FIELD, str(temperature_threshold)),
             (PSU_INFO_VOLTAGE_FIELD, str(voltage)),
             (PSU_INFO_VOLTAGE_MIN_TH_FIELD, str(voltage_low_threshold)),
             (PSU_INFO_VOLTAGE_MAX_TH_FIELD, str(voltage_high_threshold)),
             (PSU_INFO_CURRENT_FIELD, str(current)),
             (PSU_INFO_POWER_FIELD, str(power)),
             (PSU_INFO_POWER_WARNING_SUPPRESS_THRESHOLD, str(power_warning_suppress_threshold)),
             (PSU_INFO_POWER_CRITICAL_THRESHOLD, str(power_critical_threshold)),
             (PSU_INFO_POWER_OVERLOAD, str(power_exceeded_threshold)),
             (PSU_INFO_FRU_FIELD, str(is_replaceable)),
             (PSU_INFO_IN_CURRENT_FIELD, str(in_current)),
             (PSU_INFO_IN_VOLTAGE_FIELD, str(in_voltage)),
             (PSU_INFO_POWER_MAX_FIELD, str(max_power)),
             (PSU_INFO_PRESENCE_FIELD, 'true' if presence else 'false'),
             (PSU_INFO_STATUS_FIELD, 'true' if power_good else 'false'),
             (PSU_INFO_TIMESTAMP_FIELD, str(datetime.now().timestamp())),
             ])
        try:
            self.psu_tbl.set(name, fvs)
        except RuntimeError as e:
            self.log_error("Failed to update {} info to DB: {}".format(name, e))

    def _update_psu_entity_info(self):
        if not platform_chassis:
            return

        try:
            for psu in platform_chassis.get_all_psus():
                try:
                    self._update_single_psu_entity_info(psu)
                except Exception as e:
                    self.log_warning("Failed to update PSU entity data - {}".format(e))
        except NotImplementedError:
            pass
        try:
            for pdb in platform_chassis.get_all_pdbs():
                try:
                    self._update_single_psu_entity_info(pdb)
                except Exception as e:
                    self.log_warning("Failed to update PDB entity data - {}".format(e))
        except NotImplementedError:
            pass

    def _update_single_psu_entity_info(self, entity):
        name = try_get(entity.get_name, 'unknown')
        position = try_get(entity.get_position_in_parent, 0)
        fvs = swsscommon.FieldValuePairs(
            [('position_in_parent', str(position)),
             ('parent_name', CHASSIS_INFO_KEY),
             ])
        try:
            self.phy_entity_tbl.set(name, fvs)
        except RuntimeError as e:
            self.log_error("Failed to update {} entity info to DB: {}".format(name, e))

    def _update_psu_fan_data(self, entity):
        """Update FAN_INFO for fans belonging to this PSU/PDB (entity)."""
        psu_name = try_get(entity.get_name, 'unknown')
        presence = try_get(entity.get_presence, False)
        fan_list = entity.get_all_fans()
        for index, fan in enumerate(fan_list):
            fan_name = try_get(fan.get_name, '{} FAN {}'.format(psu_name, index + 1))
            direction = try_get(fan.get_direction, NOT_AVAILABLE) if presence else NOT_AVAILABLE
            speed = try_get(fan.get_speed, NOT_AVAILABLE) if presence else NOT_AVAILABLE
            status = "True" if presence else "False"
            fvs = swsscommon.FieldValuePairs(
                [(FAN_INFO_PRESENCE_FIELD, str(presence)),
                 (FAN_INFO_STATUS_FIELD, status),
                 (FAN_INFO_DIRECTION_FIELD, direction),
                 (FAN_INFO_SPEED_FIELD, str(speed)),
                 (FAN_INFO_TIMESTAMP_FIELD, datetime.now().strftime('%Y%m%d %H:%M:%S'))
                 ])
            try:
                self.fan_tbl.set(fan_name, fvs)
            except RuntimeError as e:
                self.log_error("Failed to update fan {} info to DB: {}".format(fan_name, e))

    def _set_psu_led(self, entity, psu_status):
        try:
            color = entity.STATUS_LED_COLOR_GREEN if psu_status.is_ok() else entity.STATUS_LED_COLOR_RED
            entity.set_status_led(color)
        except NotImplementedError:
            self.log_warning("set_status_led() not implemented")

    def _update_led_color(self):
        if not platform_chassis:
            return

        for name, psu_status in self.psu_status_dict.items():
            fvs = swsscommon.FieldValuePairs([
                ('led_status', str(try_get(psu_status.psu.get_status_led, NOT_AVAILABLE)))
            ])
            try:
                self.psu_tbl.set(name, fvs)
            except RuntimeError as e:
                self.log_error("Failed to update {} LED status to DB: {}".format(name, e))
            self._update_psu_fan_led_status(psu_status.psu, name)

    def _update_psu_fan_led_status(self, entity, entity_name):
        """entity: PSU or PDB object; entity_name: its name (e.g. 'PSU 1', 'PDB 1')."""
        fan_list = entity.get_all_fans()
        for index, fan in enumerate(fan_list):
            fan_name = try_get(fan.get_name, '{} FAN {}'.format(entity_name, index + 1))
            fvs = swsscommon.FieldValuePairs([
                (FAN_INFO_LED_STATUS_FIELD, str(try_get(fan.get_status_led, NOT_AVAILABLE)))
            ])
            try:
                self.fan_tbl.set(fan_name, fvs)
            except RuntimeError as e:
                self.log_error("Failed to update fan {} LED status to DB: {}".format(fan_name, e))

    def update_psu_chassis_info(self):
        if not platform_chassis:
            return

        if not self.psu_chassis_info:
            self.psu_chassis_info = PsuChassisInfo(SYSLOG_IDENTIFIER, platform_chassis)

        self.psu_chassis_info.run_power_budget(self.chassis_tbl)
        self.psu_chassis_info.update_master_status()

        if self.first_run:
            self.first_run = False


#
# Main =========================================================================
#


def main():
    psud = DaemonPsud(SYSLOG_IDENTIFIER)

    psud.log_info("Starting up...")

    while psud.run():
        pass

    psud.log_info("Shutting down...")

    return exit_code


if __name__ == '__main__':
    sys.exit(main())
