# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_out/linkmgr_grpc_driver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto_out/linkmgr_grpc_driver.proto\"-\n\x0c\x41\x64minRequest\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\r\n\x05state\x18\x02 \x03(\x08\"+\n\nAdminReply\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\r\n\x05state\x18\x02 \x03(\x08\"\"\n\x10OperationRequest\x12\x0e\n\x06portid\x18\x01 \x03(\x05\"/\n\x0eOperationReply\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\r\n\x05state\x18\x02 \x03(\x08\"\"\n\x10LinkStateRequest\x12\x0e\n\x06portid\x18\x01 \x03(\x05\"/\n\x0eLinkStateReply\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\r\n\x05state\x18\x02 \x03(\x08\"\'\n\x14ServerVersionRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\"%\n\x12ServerVersionReply\x12\x0f\n\x07version\x18\x01 \x01(\t\"-\n\x14GracefulAdminRequest\x12\x15\n\x03tor\x18\x01 \x01(\x0e\x32\x08.ToRSide\"\x8f\x01\n\x15GracefulAdminResponse\x12(\n\x07msgtype\x18\x01 \x01(\x0e\x32\x17.GracefulRestartMsgType\x12.\n\nnotifytype\x18\x02 \x01(\x0e\x32\x1a.GracefulRestartNotifyType\x12\x0c\n\x04guid\x18\x03 \x01(\t\x12\x0e\n\x06period\x18\x04 \x01(\x05*\'\n\x07ToRSide\x12\r\n\tLOWER_TOR\x10\x00\x12\r\n\tUPPER_TOR\x10\x01*<\n\x16GracefulRestartMsgType\x12\x11\n\rSERVICE_BEGIN\x10\x00\x12\x0f\n\x0bSERVICE_END\x10\x01*H\n\x19GracefulRestartNotifyType\x12\x11\n\rCONTROL_PLANE\x10\x00\x12\x0e\n\nDATA_PLANE\x10\x01\x12\x08\n\x04\x42OTH\x10\x02\x32\xc8\x02\n\rDualToRActive\x12=\n\x1dQueryAdminForwardingPortState\x12\r.AdminRequest\x1a\x0b.AdminReply\"\x00\x12;\n\x1bSetAdminForwardingPortState\x12\r.AdminRequest\x1a\x0b.AdminReply\"\x00\x12?\n\x17QueryOperationPortState\x12\x11.OperationRequest\x1a\x0f.OperationReply\"\x00\x12\x36\n\x0eQueryLinkState\x12\x11.LinkStateRequest\x1a\x0f.LinkStateReply\"\x00\x12\x42\n\x12QueryServerVersion\x12\x15.ServerVersionRequest\x1a\x13.ServerVersionReply\"\x00\x32\x62\n\x0fGracefulRestart\x12O\n\x1aNotifyGracefulRestartStart\x12\x15.GracefulAdminRequest\x1a\x16.GracefulAdminResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_out.linkmgr_grpc_driver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TORSIDE._serialized_start=574
  _TORSIDE._serialized_end=613
  _GRACEFULRESTARTMSGTYPE._serialized_start=615
  _GRACEFULRESTARTMSGTYPE._serialized_end=675
  _GRACEFULRESTARTNOTIFYTYPE._serialized_start=677
  _GRACEFULRESTARTNOTIFYTYPE._serialized_end=749
  _ADMINREQUEST._serialized_start=39
  _ADMINREQUEST._serialized_end=84
  _ADMINREPLY._serialized_start=86
  _ADMINREPLY._serialized_end=129
  _OPERATIONREQUEST._serialized_start=131
  _OPERATIONREQUEST._serialized_end=165
  _OPERATIONREPLY._serialized_start=167
  _OPERATIONREPLY._serialized_end=214
  _LINKSTATEREQUEST._serialized_start=216
  _LINKSTATEREQUEST._serialized_end=250
  _LINKSTATEREPLY._serialized_start=252
  _LINKSTATEREPLY._serialized_end=299
  _SERVERVERSIONREQUEST._serialized_start=301
  _SERVERVERSIONREQUEST._serialized_end=340
  _SERVERVERSIONREPLY._serialized_start=342
  _SERVERVERSIONREPLY._serialized_end=379
  _GRACEFULADMINREQUEST._serialized_start=381
  _GRACEFULADMINREQUEST._serialized_end=426
  _GRACEFULADMINRESPONSE._serialized_start=429
  _GRACEFULADMINRESPONSE._serialized_end=572
  _DUALTORACTIVE._serialized_start=752
  _DUALTORACTIVE._serialized_end=1080
  _GRACEFULRESTART._serialized_start=1082
  _GRACEFULRESTART._serialized_end=1180
# @@protoc_insertion_point(module_scope)
